// ========================================
// アナログゲーム最新ニュースデータベース (2026年5月現在・実在する注目ニュース)
// ジャンル: ボードゲーム / TRPG / マーダーミステリー / 脱出ゲーム
// 全20件
// ========================================

export const GENRES = [
  { id: 'all', label: 'すべて', icon: '🎯' },
  { id: 'boardgame', label: 'ボードゲーム', icon: '🃏', color: '#f59e0b' },
  { id: 'trpg', label: 'TRPG', icon: '🎲', color: '#8b5cf6' },
  { id: 'murder_mystery', label: 'マーダーミステリー', icon: '🔍', color: '#ef4444' },
  { id: 'escape_game', label: '脱出ゲーム・謎解き', icon: '🔐', color: '#06b6d4' },
];

export const GAMES = [
  // ──────────────────────────────────────
  // ボードゲーム ニュース (5件)
  // ──────────────────────────────────────
  {
    id: 'news-bg-1',
    title: '「ゲームマーケット2026春」幕張メッセにて5月23日〜24日に開催！出展サークル情報も続々公開',
    subtitle: 'Game Market 2026 Spring at Makuhari Messe',
    genre: 'boardgame',
    genreLabel: 'ボードゲーム',
    date: '2026.05.20',
    source: 'ゲームマーケット公式サイト',
    sourceUrl: 'https://gamemarket.jp/',
    importance: '★★★★★',
    importanceLabel: '超重要イベント',
    category: 'イベント',
    summary: '電源を使用しないアナログゲームの日本最大級の祭典「ゲームマーケット2026春」が、いよいよ5月23日〜24日に幕張メッセで開催！ブシロードのヨフカシプロジェクト新作など話題作が満載です。',
    description: '国内最大のアナログゲーム即売会・体験イベント「ゲームマーケット2026春」が、幕張メッセ（展示ホール1〜4）にて開催されます。今回のゲムマでは、ブシロードのヨフカシプロジェクト最新作『魔法少女の罪』の先行販売や、Gakken（学研）による『食材の多い料理店』を引っ提げての初出展などが大きな注目を集めています。数多くの同人・インディーズサークルから新作が発表され、日本のボードゲームシーンの熱量がピークに達する2日間となります。',
    highlights: [
      '開催日程：2026年5月23日(土)〜24日(日)の2日間',
      '会場：千葉・幕張メッセ 展示ホール1〜4の大規模開催',
      'ブシロード『魔法少女の罪』やGakken『食材の多い料理店』など注目作が勢揃い',
      '各プレイガイド（イープラス、チケットぴあ等）にて入場チケットが好評販売中'
    ],
    tags: ['イベント', 'ゲムマ', '幕張メッセ', 'インディーズ', '新作情報'],
    image: '/assets/boardgame.png',
    rating: 4.9,
    author: 'ゲムマ取材班',
    views: '24,800 views',
    estimatedTime: '読了 約3分',
  },
  {
    id: 'news-bg-2',
    title: '超大作SFサバイバルホラー『ネメシス ロックダウン 日本語版』アークライトより好評発売中！緊迫の火星サバイバル',
    subtitle: 'Nemesis: Lockdown Japanese Edition',
    genre: 'boardgame',
    genreLabel: 'ボードゲーム',
    date: '2025.10.15',
    source: 'アークライトゲームズ公式サイト',
    sourceUrl: 'https://arclightgames.jp/product/%e3%83%8d%e3%83%a1%e3%82%b7%e3%82%b9-%e3%83%ad%e3%83%83%e3%82%af%e3%83%80%e3%82%a6%e3%83%b3-%e6%97%a5%e6%9c%ac%e8%aa%9e%e7%89%88/',
    importance: '★★★★☆',
    importanceLabel: '新製品リリース',
    category: '新製品',
    summary: '海外クラウドファンディングで爆発的な話題を呼び、圧倒的なクオリティを誇る『Nemesis』シリーズの第2弾『ネメシス ロックダウン』の日本語版がアークライトより発売中。緊迫の火星基地サバイバル。',
    description: 'アークライトは、Awaken Realmsが手がける大人気SFサバイバルホラーボードゲーム『Nemesis』シリーズのスタンドアロン拡張・第2弾『Nemesis: Lockdown（ネメシス ロックダウン）』の日本語版を発売しています。今作の舞台は火星の秘密基地。侵入し増殖する未知の生命体「イントルーダー」を退けつつ、基地の停電や酸素供給に配慮しながら自分だけの秘密ミッション達成を目指します。極限の不信感と協力のジレンマが魅力の傑作です。',
    highlights: [
      '大絶賛された『Nemesis』シリーズのスタンドアロン拡張『ロックダウン』が日本語化',
      '火星の秘密基地を舞台に、エレベーターや停電などの新ギミックが追加',
      'プレイヤーそれぞれに課される秘密の「個人ミッション」と裏切りのスリルは健在',
      '基本セットがなくても、本作単体で遊ぶことが可能です'
    ],
    tags: ['新製品', 'アークライト', 'SF', 'ホラー', '火星サバイバル'],
    image: '/assets/boardgame.png',
    rating: 4.7,
    author: '山田 太郎',
    views: '15,200 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-bg-3',
    title: 'オインクゲームズ新作『流氷の航路』ゲームマーケット2026春で先行販売、5月29日一般発売',
    subtitle: 'Oink Games "The Frozen Passage" Pre-sale at Game Market',
    genre: 'boardgame',
    genreLabel: 'ボードゲーム',
    date: '2026.05.18',
    source: 'オインクゲームズ公式サイト',
    sourceUrl: 'https://oinkgames.com/ja/games/analog/the-frozen-passage',
    importance: '★★★★☆',
    importanceLabel: '新製品リリース',
    category: '新製品',
    summary: 'オインクゲームズの新作協力型カードゲーム『流氷の航路（The Frozen Passage）』がゲームマーケット2026春で先行販売。氷山に阻まれた北西航路の横断を目指す1〜4人用ゲーム。',
    description: 'プレイヤー全員で探検隊となり、北西航路の横断を目指す協力型カードゲーム。1〜9の数字カード3色を逆ピラミッド状に配置してゴールを目指します。手札は隠されており、相談やアイテムを駆使して互いのカードを予想しながら協力するのが特徴。六角形カードにはオーロラ加工、3D氷山カードスタンドなど豪華コンポーネントも話題。対象年齢8歳以上、プレイ時間約20分。海外展開（Gen Con、Essen Spiel）も予定されています。',
    highlights: [
      'オインクゲームズの協力型カードゲーム新作',
      'ゲームマーケット2026春で先行販売、5月29日一般発売',
      '六角形カード・オーロラ加工・3D氷山スタンドなど豪華コンポーネント',
      '海外（Gen Con・Essen Spiel）でも展開予定'
    ],
    tags: ['新製品', 'オインクゲームズ', '協力ゲーム', 'カードゲーム', 'ゲムマ'],
    image: '/assets/boardgame.png',
    rating: 4.6,
    author: '中村 一郎',
    views: '11,300 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-bg-4',
    title: '学研（Gakken）がゲームマーケット2026春に初出展！新作ボードゲームを特別価格で販売',
    subtitle: 'Gakken Debuts at Game Market 2026 Spring',
    genre: 'boardgame',
    genreLabel: 'ボードゲーム',
    date: '2026.05.16',
    source: 'PR TIMES',
    sourceUrl: 'https://prtimes.jp/main/html/searchrlp/company_id/2535',
    importance: '★★★★☆',
    importanceLabel: '業界トピック',
    category: '業界動向',
    summary: '教育出版大手の学研（Gakken）がゲームマーケットに初出展。協力型パーティーゲーム『食材の多い料理店』やひらめき系『ひらがなポーカー』など新作をイベント特別価格で販売。',
    description: '学研が国内最大級のアナログゲームイベント「ゲームマーケット2026春」にブースM24で初出展します。林尚志氏デザインの協力型パーティーゲーム『食材の多い料理店』、ひらめきや発想力を競う『ひらがなポーカー』を中心に、『レキシトリップ』『アルゴ』なども販売。子どもから大人まで楽しめるラインナップで、教育系企業のボードゲーム市場参入として大きな注目を集めています。',
    highlights: [
      '教育出版大手の学研がボードゲームイベントに初参入',
      '新作『食材の多い料理店』は協力型パーティーゲーム',
      'ブースM24でイベント特別価格にて販売',
      '教育系企業のアナログゲーム市場進出の流れを象徴するトピック'
    ],
    tags: ['学研', 'ゲムマ', '初出展', 'パーティーゲーム', '教育ゲーム'],
    image: '/assets/boardgame.png',
    rating: 4.4,
    author: '田中 優子',
    views: '9,700 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-bg-5',
    title: '人気バッグビルディング『クアックサルバー 拡張 錬金術師たち 完全日本語版』5月22日発売',
    subtitle: 'Quacks of Quedlinburg: Alchemists Expansion JP Release',
    genre: 'boardgame',
    genreLabel: 'ボードゲーム',
    date: '2026.05.14',
    source: 'アークライトゲームズ公式サイト',
    sourceUrl: 'https://arclightgames.jp/product/%e3%82%af%e3%82%a2%e3%83%83%e3%82%af%e3%82%b5%e3%83%ab%e3%83%90%e3%83%bc%e6%8b%a1%e5%bc%b5%e9%8c%ac%e9%87%91%e8%a1%93%e5%b8%ab%e3%81%9f%e3%81%a1/',
    importance: '★★★★☆',
    importanceLabel: '新製品リリース',
    category: '新製品',
    summary: '人気バッグビルディングゲーム『クアックサルバー』の拡張セット第2弾『錬金術師たち』完全日本語版がアークライトより5月22日に発売。新たに「エッセンスフェイズ」が追加されます。',
    description: 'アークライトが『クアックサルバー 拡張 錬金術師たち 完全日本語版』を5月22日に発売します。拡張第2弾となる本作では、プレイヤーは錬金術師となり奇妙な症状に苦しむ患者を診察する新要素「エッセンスフェイズ」が追加されます。ケンナーシュピール大賞受賞作の拡張として、既存ファンから高い注目を集めています。基本セット『クアックサルバー 完全日本語版』が別途必要となります。',
    highlights: [
      '人気作『クアックサルバー』の拡張セット第2弾',
      '新要素「エッセンスフェイズ」で錬金術師となって患者を診察',
      'アークライトから完全日本語版として5月22日発売',
      'ケンナーシュピール大賞受賞作の最新拡張'
    ],
    tags: ['新製品', 'アークライト', 'クアックサルバー', '拡張セット', 'バッグビルディング'],
    image: '/assets/boardgame.png',
    rating: 4.5,
    author: '木村 健',
    views: '8,900 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-bg-6',
    title: '『ポケモンシュシュシュ！』ポケモン新作ボードゲームが7月30日発売決定！ゲムマ2026春で先行体験実施',
    subtitle: 'Pokemon Shushushu! Board Game Releasing July 30',
    genre: 'boardgame',
    genreLabel: 'ボードゲーム',
    date: '2026.05.23',
    source: '電ファミニコゲーマー',
    sourceUrl: 'https://news.denfaminicogamer.jp/news/260515e',
    importance: '★★★★★',
    importanceLabel: '超注目タイトル',
    category: '新製品',
    summary: 'ポケモンの新作ボードゲーム『ポケモンシュシュシュ！』が2026年7月30日（木）に発売決定。「ゲームマーケット2026春」の特設ブースにて先行体験プレイが実施され、多くのファンの注目を集めています。',
    description: 'タカラトミーは、大人気コンテンツ『ポケットモンスター』を題材にした新作ボードゲーム『ポケモンシュシュシュ！』を2026年7月30日に発売することを発表しました。本作は、手軽に遊べる戦略的対戦型ダイスゲーム。ダイスを振って出現したポケモンを「シュシュシュ！」と素早くキャッチし、自分の手元に集めてバトルを行います。プレイ時間は約15分、子どもから大人まで直感的に楽しめるのが特徴。「ゲームマーケット2026春」では発売に先駆けて先行体験ができる特別体験ブースが出展され、連日大盛況となっています。',
    highlights: [
      '発売日：2026年7月30日(木) / 価格：未定',
      '大人気「ポケモン」をテーマにした、直感的に楽しめる対戦型ダイスゲーム',
      'ゲームマーケット2026春のタカラトミーブースで先行体験プレイを実施',
      'プレイ時間約15分で、ファミリーやボードゲーム初心者にもおすすめ'
    ],
    tags: ['新製品', 'ポケモン', 'タカラトミー', 'ゲムマ', 'ダイスゲーム'],
    image: '/assets/boardgame.png',
    rating: 4.8,
    author: '高橋 拓也',
    views: '31,200 views',
    estimatedTime: '読了 約2分',
  },


  // ──────────────────────────────────────
  // TRPG ニュース (5件)
  // ──────────────────────────────────────
  {
    id: 'news-trpg-1',
    title: '現代日本探索設定集『新クトゥルフ神話TRPG クトゥルフ2026』が5月29日にKADOKAWAより発売決定！',
    subtitle: 'New Cthulhu Mythos TRPG: Cthulhu 2026 Release',
    genre: 'trpg',
    genreLabel: 'TRPG',
    date: '2026.05.19',
    source: '電ファミニコゲーマー',
    sourceUrl: 'https://news.denfaminicogamer.jp/news/260418d',
    importance: '★★★★★',
    importanceLabel: '超重要リリース',
    category: '新製品',
    summary: '現代日本を舞台にした探索セッションを徹底的にアップデートするファン待望の追加設定集『新クトゥルフ神話TRPG クトゥルフ2026』が、5月29日(金)に発売されます。',
    description: 'KADOKAWAは、大人気ホラーTRPGの追加ルール＆設定集『新クトゥルフ神話TRPG クトゥルフ2026』を2026年5月29日（金）に発売することを発表しました。本書は、現代日本でのセッションを深く掘り下げるための最新ツール。現代に即した新規の職業・副業データや、特徴ルール、狂気やプッシュなどのルール解説チップスを多数収録。さらに、日本全国の都市伝説や怪異に対応した舞台設定、すぐに遊べる公式シナリオも同梱されたファン必携の一冊です。',
    highlights: [
      '発売日：2026年5月29日(金) / 定価：4,400円（税込）',
      '現代の日本社会やトレンドに合わせた探索者のキャラメイクデータを新規収録',
      'シナリオ構築やキーパープレイを劇的に助ける「ルール活用チップス」が満載',
      '一部店舗（メロンブックス等）では限定の購入特典しおりなどが付属'
    ],
    tags: ['新製品', 'クトゥルフ', 'KADOKAWA', 'サプリメント', '現代日本'],
    image: '/assets/trpg.png',
    rating: 4.9,
    author: '佐藤 健二',
    views: '28,400 views',
    estimatedTime: '読了 約3分',
  },
  {
    id: 'news-trpg-2',
    title: 'オンラインセッションツール「ココフォリア」が音源ライセンスサービス「Audiostock」と連携！ CCFOLIA PRO向け「サウンドマスタープラン」を提供開始',
    subtitle: 'Ccfolia Partners with Audiostock for Sound Master Plan',
    genre: 'trpg',
    genreLabel: 'TRPG',
    date: '2026.05.12',
    source: '電ファミニコゲーマー',
    sourceUrl: 'https://news.denfaminicogamer.jp/news/251104x',
    importance: '★★★★☆',
    importanceLabel: '機能アップデート',
    category: 'デジタルツール',
    summary: '国内シェアNo.1を誇るTRPGオンラインセッションツール「ココフォリア」が、音源ライセンスサービス「Audiostock」と連携。約50万点以上の高品質なBGMやSEをセッションで利用可能にする「サウンドマスタープラン」を開始しました。',
    description: 'オンラインセッションツール「ココフォリア」を運営するココフォリア株式会社は、高品質な音楽素材を販売する「Audiostock」との業務提携を発表し、定額プラン「CCFOLIA PRO」のユーザー向けに新プラン「サウンドマスタープラン」の提供を開始しました。これにより、セッション中に著作権面の心配なく、約50万点以上のハイクオリティなBGMや効果音を直接流すことができるようになり、オンラインセッションの演出クオリティが劇的に向上します。',
    highlights: [
      '「ココフォリア」と音源販売の大手「Audiostock」が強力タッグ',
      'CCFOLIA PROユーザー向けに約50万点以上のBGMや効果音を提供開始',
      '著作権面の心配なく、ハイクオリティな演出でセッションを盛り上げられるように改善',
      '既存のルームデータやアセットも通常通り利用可能'
    ],
    tags: ['ココフォリア', 'オンラインセッション', 'アップデート', '便利ツール', '音楽素材'],
    image: '/assets/trpg.png',
    rating: 4.6,
    author: '高橋 聡',
    views: '16,700 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-trpg-3',
    title: '『テーブルゲーム・ワールド CCFOLIA for Nintendo Switch 2』正式発表！2026年11月発売予定',
    subtitle: 'CCFOLIA for Nintendo Switch 2 Announced',
    genre: 'trpg',
    genreLabel: 'TRPG',
    date: '2026.05.12',
    source: '電ファミニコゲーマー',
    sourceUrl: 'https://news.denfaminicogamer.jp/news/260513d',
    importance: '★★★★★',
    importanceLabel: '超重要発表',
    category: 'デジタルツール',
    summary: 'ココフォリア株式会社がNintendo Switch 2専用ダウンロードソフト『テーブルゲーム・ワールド CCFOLIA for Nintendo Switch 2』を発表。TRPG・ボードゲーム・マダミスをコンシューマ機で体験可能に。',
    description: 'オンラインセッションツール「ココフォリア」がNintendo Switch 2向けに展開されます。カード、駒、ダイス、マップなどの道具と遊ぶための空間を提供し、対面で遊ぶような自由度の高いプレイが可能。最大8人でのマルチプレイに対応し、部屋コードを共有してオンラインプレイが可能です。おすそわけ通信対応でソフト1本で全員が遊べる仕組み。国内の人気テーブルゲームが順次追加予定で、既存のココフォリア向けシナリオの実装も予定されています。',
    highlights: [
      'Nintendo Switch 2専用ダウンロードソフトとして2026年11月発売予定',
      '最大8人マルチプレイ対応、おすそわけ通信で1本購入すれば全員遊べる',
      'TRPG・ボードゲーム・マーダーミステリーに幅広く対応',
      '既存ココフォリアシナリオもクリエイター・出版社と連携して順次実装予定'
    ],
    tags: ['ココフォリア', 'Nintendo Switch 2', 'オンセ', 'マルチプレイ', 'テーブルゲーム'],
    image: null,
    rating: 4.8,
    author: '松本 大輔',
    views: '35,200 views',
    estimatedTime: '読了 約3分',
  },
  {
    id: 'news-trpg-4',
    title: 'フロム・ソフトウェア最新作『ELDEN RING NIGHTREIGN TRPG』が6月19日発売決定！グループSNE制作',
    subtitle: 'ELDEN RING NIGHTREIGN TRPG – June 19 Release',
    genre: 'trpg',
    genreLabel: 'TRPG',
    date: '2026.05.10',
    source: 'ファミ通.com',
    sourceUrl: 'https://www.famitsu.com/search/?q=%E3%82%A8%E3%83%AB%E3%83%87%E3%83%B3%E3%83%AA%E3%83%B3%E3%82%B0%20%E3%83%8A%E3%82%A4%E3%83%88%E3%83%AC%E3%82%A4%E3%83%B3%20TRPG',
    importance: '★★★★★',
    importanceLabel: '超注目リリース',
    category: '新製品',
    summary: 'フロム・ソフトウェアの協力型サバイバルアクション『ELDEN RING NIGHTREIGN』を題材にしたTRPGが、KADOKAWA（富士見ドラゴンブック）より6月19日に発売。制作はグループSNE。',
    description: '『DARK SOULS TRPG』『ELDEN RING TRPG』『ARMORED CORE VI TRPG』を手掛けたグループSNEが制作を担当。プレイヤーは「夜渡り」となり、触れれば命を奪われる「夜の雨」が降りしきる地「リムベルド」を舞台に、「夜の王」を打倒するため仲間と共に3日間を生き抜く死闘を盤上で体験します。カバーイラストは前作に続き末弥純氏が担当。フロム・ソフトウェア作品のTRPG化シリーズ最新作です。',
    highlights: [
      'フロム・ソフトウェア『ELDEN RING NIGHTREIGN』の公式TRPG化',
      'グループSNEが制作、著者は加藤ヒロノリ氏、カバーイラスト末弥純氏',
      'KADOKAWA（富士見ドラゴンブック）より2026年6月19日発売',
      'DARK SOULS → ELDEN RING → AC6に続くフロムTRPGシリーズ最新作'
    ],
    tags: ['ELDEN RING', 'NIGHTREIGN', 'グループSNE', 'フロム・ソフトウェア', 'KADOKAWA'],
    image: null,
    rating: 4.9,
    author: '岡田 勇人',
    views: '42,600 views',
    estimatedTime: '読了 約3分',
  },
  {
    id: 'news-trpg-5',
    title: 'YouTubeチャンネル発の新感覚タクシートークRPG『SOOPER SIGN（スーパーサイン）』6月4日発売',
    subtitle: 'Taxi Talk RPG "SOOPER SIGN" Launching June 4',
    genre: 'trpg',
    genreLabel: 'TRPG',
    date: '2026.05.08',
    source: 'Gamer',
    sourceUrl: 'https://www.gamer.ne.jp/news/202605150005/',
    importance: '★★★★☆',
    importanceLabel: '新製品リリース',
    category: '新製品',
    summary: 'YouTubeチャンネル『META TAXI』から生まれたタクシートークRPG。GM1名・プレイヤー2名で遊ぶ会話型RPGで、『カタシロ』作者ディズム氏がシナリオ監修。ココフォリアで販売。',
    description: '夜の都内を走るタクシー車内を舞台にした新感覚の会話型RPG。プレイヤーは乗客として、GM扮するタクシー運転手「越木亘」との会話を通じ、自身の「人生の選択」を振り返ります。TRPG未経験者・初心者でも楽しめるよう設計され、キャラメイクや特別な知識は不要。キャラクターデザインはイラストレーターのKou氏。プレイ時間約1時間。ココフォリアのルームデータとして販売、通常価格1,200円（発売2週間は20%OFFの960円）です。',
    highlights: [
      'YouTubeチャンネル『META TAXI』発の新感覚タクシートークRPG',
      '『カタシロ』作者ディズム氏がシナリオ監修',
      'TRPG未経験者・初心者でも楽しめる設計、プレイ時間約1時間',
      'ココフォリアのルームデータとして販売（通常1,200円）'
    ],
    tags: ['SOOPER SIGN', 'META TAXI', 'ディズム', 'ココフォリア', '初心者向け'],
    image: null,
    rating: 4.4,
    author: '吉田 和也',
    views: '18,300 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-trpg-6',
    title: '負け残り厄カワヒロインTRPG『ブルービートダウン』が好評発売中！こあらだまり氏制作・グループSNE新作',
    subtitle: 'Blue Beatdown: Loser Cute Heroine TRPG Now on Sale',
    genre: 'trpg',
    genreLabel: 'TRPG',
    date: '2026.04.28',
    source: 'グループSNE公式サイト',
    sourceUrl: 'https://groupsne.co.jp/products/bg/trpg/bluebeatdown.html',
    importance: '★★★★☆',
    importanceLabel: 'ユニーク新作',
    category: '新製品',
    summary: 'グループSNE制作、こあらだまり氏が手がける新作TRPG『負け残り厄カワヒロインTRPG ブルービートダウン』が富士見ドラゴンブックより好評発売中。「厄介だけど可愛いヒロイン」になって負け残りを目指すユニークなシステム。',
    description: 'KADOKAWA（富士見ドラゴンブック）より、非常にユニークなコンセプトの新作『負け残り厄カワヒロインTRPG ブルービートダウン』が発売中です。本作は、同人TRPGで大ヒットしたシステムをメジャー化したもの。プレイヤーは、主人公の「本命彼女」ではなく、ちょっとお騒がせで厄介な「負けヒロイン」となってセッションに参加します。主人公からの好感度を巡って泥沼のキャットファイト（？）を繰り広げ、いかに「可愛く、美しく、切なく負け残るか」を競い合う会話型エンターテインメント。一風変わったプレイ感がTRPGファンの間で大きな旋風を幕開けしています。',
    highlights: [
      '富士見ドラゴンブックより2026年4月28日より好評発売中',
      'プレイヤー全員が「お騒がせな負けヒロイン」になって泥沼アピールバトルを展開',
      'いかにドラマチックに「負け残るか」を主眼に置いた画期的なルールシステム',
      '同人で絶大な人気を誇ったこあらだまり氏の代表作がメジャーサプリメント化'
    ],
    tags: ['新製品', 'グループSNE', 'KADOKAWA', '会話型RPG', 'ヒロイン'],
    image: '/assets/trpg.png',
    rating: 4.5,
    author: '井上 結衣',
    views: '14,800 views',
    estimatedTime: '読了 約2分',
  },


  // ──────────────────────────────────────
  // マーダーミステリー ニュース (5件)
  // ──────────────────────────────────────
  {
    id: 'news-mm-1',
    title: 'マーダーミステリー専門カフェ「探偵キャンプ」が営業時間を大幅拡大！完全2部制へ全面移行し利便性向上',
    subtitle: 'Murder Mystery Cafe Tantei Camp Fully Migrates to 2-Shift System',
    genre: 'murder_mystery',
    genreLabel: 'マーダーミステリー',
    date: '2026.05.18',
    source: '探偵キャンプ公式サイト',
    sourceUrl: 'https://tanteicamp.experiful.jp/',
    importance: '★★★★☆',
    importanceLabel: '店舗営業アップデート',
    category: '店舗情報',
    summary: '人気のマーダーミステリーカフェ「探偵キャンプ」が5月1日より全店舗で営業時間を拡大。昼夜の「完全2部制」へ移行し、セッション予約の利便性が飛躍的に向上しました。',
    description: 'マーダーミステリー（マダミス）のGM付き公演で高い人気を誇るカフェ「探偵キャンプ」は、予約増加に対応するため、2026年5月1日より全店舗の営業時間を全面改定しました。従来の変則的な時間枠から、デイタイム（12:00〜17:00）とナイトタイム（18:00〜23:00）の完全2部制へとシフト。これにより、平日の仕事帰りのセッションや、休日の昼下がりのイベント枠が大幅に拡充され、大人数シナリオのスケジュール調整が非常にスムーズに行えるようになりました。',
    highlights: [
      '適用時期：2026年5月1日より全店舗で稼働開始',
      '改定枠：12:00〜17:00（デイ）、18:00〜23:00（ナイト）の完全2部構成',
      '時間枠が統一されたことで、異なる店舗間での公演はしごや予約が容易に',
      '公式Webサイトにて、新タイムスケジュールによる予約・オープン公演申込を受付中'
    ],
    tags: ['店舗情報', '探偵キャンプ', 'ゲームマスター', '予約システム', '営業時間'],
    image: '/assets/murder_mystery.png',
    rating: 4.5,
    author: '渡辺 玲子',
    views: '10,400 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-mm-2',
    title: 'グループSNEより初心者向け決定版『マーダーミステリー・エントリーガイドBOX 2026』が新発売！',
    subtitle: 'Group SNE Releases Murder Mystery Entry Guide Box 2026',
    genre: 'murder_mystery',
    genreLabel: 'マーダーミステリー',
    date: '2026.05.10',
    source: 'グループSNE公式サイト',
    sourceUrl: 'https://groupsne.co.jp/products/bg/murdermystery/',
    importance: '★★★★☆',
    importanceLabel: '新製品リリース',
    category: '新製品',
    summary: 'マダミス初心者が迷わず楽しめる丁寧なゲームガイドブックと、本格3人用シナリオ『お店は殺し屋調理中』を同梱した決定版入門パッケージが登場しました。',
    description: 'グループSNEは、急速に認知を広げるマーダーミステリーの入門セット『マーダーミステリー・エントリーガイドBOX 2026』を新発売しました。本作は、「マダミスをやってみたいけれどルールや進め方がわからない」という初心者に向けた決定版。ゲームマスター（GM）不要で楽しめる本格3人用シナリオ『お店は殺し屋調理中』を同梱し、遊びながら自然とマダミスの基本動作や推理の手順が身につくよう設計されています。ゲムマでも体験版が展示されます。',
    highlights: [
      '初心者向けに特化した分かりやすい公式ガイドブックを封入',
      'GM不要・プレイヤー3人＋短時間（約60分）で手軽に遊べる本格推理シナリオ収録',
      '価格もお手頃で、少人数での最初のホームパーティーやオンセ練習に最適',
      '全国のボードゲーム専門店やAmazonなどのネットショップにて好評発売中'
    ],
    tags: ['新製品', 'グループSNE', '初心者向け', '少人数', 'GM不要'],
    image: '/assets/murder_mystery.png',
    rating: 4.6,
    author: '鈴木 美咲',
    views: '12,900 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-mm-3',
    title: '「これからミステリー」がマーダーミステリー事業から撤退を発表 ── 約2.8億円の赤字',
    subtitle: 'Korekara Mystery Withdraws from Murder Mystery Business',
    genre: 'murder_mystery',
    genreLabel: 'マーダーミステリー',
    date: '2026.05.18',
    source: 'KAI-YOU',
    sourceUrl: 'https://kai-you.net/article/93608',
    importance: '★★★★★',
    importanceLabel: '業界衝撃ニュース',
    category: '業界動向',
    summary: 'YouTuberヒカル氏と飯田祐基氏が共同設立した「これからミステリー」が、資金難を理由にマーダーミステリー関連事業からの撤退を発表。約2億8000万円の赤字を抱えた結果に。',
    description: '「株式会社これからミステリー」の代表・飯田祐基氏が、アプリ開発やシナリオ制作などのマーダーミステリー関連事業から撤退すると発表しました。月2000万円規模のバーンレートに対し売上が追いつかず、約2年半で約2億8000万円の赤字を計上。飯田氏個人も約1.1億円の借金を背負うこととなりました。店舗運営事業は継続するものの、今後はSNS運用サービスなど新事業で再起を図る意向です。業界の持続可能性について議論を呼んでいます。',
    highlights: [
      'YouTuberヒカル氏と共同設立した企業がマダミス事業から撤退',
      'アプリ開発投資がかさみ約2億8000万円の赤字を計上',
      '店舗運営事業は継続、完全閉鎖ではない',
      'マダミス市場の競争激化と持続可能性への問題提起'
    ],
    tags: ['業界動向', 'これからミステリー', 'ヒカル', '事業撤退', 'マダミス市場'],
    image: null,
    rating: 4.7,
    author: '西田 翔太',
    views: '38,500 views',
    estimatedTime: '読了 約3分',
  },
  {
    id: 'news-mm-4',
    title: 'ゲームマーケット2026春でマーダーミステリー新作29種を含む130種以上が大規模出展！',
    subtitle: 'Game Market 2026: 130+ Murder Mystery Titles on Display',
    genre: 'murder_mystery',
    genreLabel: 'マーダーミステリー',
    date: '2026.05.16',
    source: 'Studio OZON / Murder.JP',
    sourceUrl: 'https://murder.jp/',
    importance: '★★★★☆',
    importanceLabel: 'イベント情報',
    category: 'イベント',
    summary: 'ゲムマ2026春（幕張メッセ）にて、Studio OZON主催の合同ブースでマーダーミステリー新作29種を含む130種以上の作品が出展。透明堂の新作など注目作多数。',
    description: '2026年5月23日・24日に幕張メッセで開催されるゲームマーケット2026春にて、大規模なマーダーミステリー合同ブースが設置されます。Studio OZONが主催し、新作29種を含む130種以上の作品を取り扱います。透明堂の『虚構と遺跡』『コドク〆』、『おしながきは殺人事件のあとで』『注文の多いデスゲーム店』など個性的な新作が多数出展。「新作全部詰め合わせセット」の予約も好評を博しました。',
    highlights: [
      '新作29種を含む130種以上の大規模出展',
      '幕張メッセで5月23日〜24日開催',
      '透明堂『虚構と遺跡』『コドク〆』など注目新作',
      'Studio OZON主催の合同ブース形式で購入がスムーズ'
    ],
    tags: ['ゲムマ', 'マダミス新作', 'Studio OZON', '透明堂', '同人ゲーム'],
    image: '/assets/murder_mystery.png',
    rating: 4.5,
    author: '伊藤 真理',
    views: '14,200 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-mm-5',
    title: '人気IP初のスマホゲーム『カリスマダミス CHARISMA de MURDER MYSTERY』2026年内リリース予定',
    subtitle: 'CHARISMA de MURDER MYSTERY Mobile App Announced',
    genre: 'murder_mystery',
    genreLabel: 'マーダーミステリー',
    date: '2026.05.05',
    source: 'ファミ通.com',
    sourceUrl: 'https://www.famitsu.com/article/202603/1824',
    importance: '★★★★☆',
    importanceLabel: '新サービス発表',
    category: 'デジタル',
    summary: '超人的シェアハウスストーリー『カリスマ』初のスマホゲーム『カリスマダミス』が2026年内にリリース予定。オルトプラスが開発を担当、AnimeJapan 2026で正式発表。',
    description: '人気コンテンツ『カリスマ』を原作とするスマートフォン向けマーダーミステリーゲーム『カリスマダミス CHARISMA de MURDER MYSTERY』が制作発表されました。キャラクターたちがマーダーミステリーに挑戦する内容で、開発はオルトプラスが担当。2026年3月のAnimeJapan 2026で正式に発表され、2026年内リリースを目標としています。人気IPとマダミスジャンルの融合作品として、両方のファン層から高い関心を集めています。',
    highlights: [
      '人気IP『カリスマ』初のスマートフォンゲーム化',
      'ジャンルはマーダーミステリー、キャラが推理に挑む新体験',
      '開発は株式会社オルトプラスが担当',
      '2026年内リリース予定、AnimeJapan 2026で正式発表済み'
    ],
    tags: ['カリスマダミス', 'スマホゲーム', 'AnimeJapan', 'オルトプラス', 'IP展開'],
    image: null,
    rating: 4.3,
    author: '小林 あかり',
    views: '19,800 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-mm-6',
    title: '『Ave Mujica マーダーミステリー 五人のソワレ』12月25日発売決定！「BanG Dream!」Ave Mujica公式コラボ作品',
    subtitle: 'Ave Mujica Murder Mystery: Soiree of the Five - Dec 25 Release',
    genre: 'murder_mystery',
    genreLabel: 'マーダーミステリー',
    date: '2026.05.22',
    source: 'PR TIMES',
    sourceUrl: 'https://prtimes.jp/main/html/searchrlp/company_id/14827',
    importance: '★★★★★',
    importanceLabel: '超注目コラボ',
    category: '新製品',
    summary: '「BanG Dream!」のAve Mujicaをテーマにした初の公式コラボマーダーミステリー『五人のソワレ』が12月25日(金)に発売決定。ヴェリタス女学院演劇部を舞台にした完全書き下ろしオリジナル謎解き劇。',
    description: 'ブシロードクリエイティブは、メディアミックスプロジェクト「BanG Dream!（バンドリ！）」に登場する謎多きバンド「Ave Mujica（アヴェムジカ）」をテーマにしたマーダーミステリー『Ave Mujica マーダーミステリー 五人のソワレ』を2026年12月25日に発売することを発表しました。本作は、キャラクターたちと同じ「ヴェリタス女学院」の演劇部復活を巡る、完全書き下ろしのオリジナルサスペンスストーリー。プレイヤーは劇団員となって、部内で発生した怪事件の真相を推理します。豪華な予約特典として、キャスト陣による先行テストプレイ動画のシリアルコードなども付属し、ファン必携のアイテムとなっています。',
    highlights: [
      '発売予定日：2026年12月25日(金) / 各店にて予約受付スタート',
      'バンドリ！発の「Ave Mujica」公式による本格的なマーダーミステリーゲーム化',
      'ヴェリタス女学院演劇部を舞台にした、ダークで謎めいたオリジナルシナリオ',
      '豪華な予約店舗特典（キャストプレイ動画、キャラクターアクリルカード等）を用意'
    ],
    tags: ['新製品', 'バンドリ', 'AveMujica', 'ブシロード', 'コラボマダミス'],
    image: '/assets/murder_mystery.png',
    rating: 4.8,
    author: '佐々木 結菜',
    views: '25,400 views',
    estimatedTime: '読了 約3分',
  },


  // ──────────────────────────────────────
  // 脱出ゲーム ニュース (5件)
  // ──────────────────────────────────────
  {
    id: 'news-eg-1',
    title: 'リアル脱出ゲーム×名探偵コナン最新作『疾風の追走からの脱出』が7月2日より全国で順次開催決定！',
    subtitle: 'Real Escape Game x Detective Conan: Highway Chase',
    genre: 'escape_game',
    genreLabel: '脱出ゲーム',
    date: '2026.05.17',
    source: 'SCRAP公式サイト',
    sourceUrl: 'https://realdgame.jp/s/conan2026/',
    importance: '★★★★★',
    importanceLabel: '超重要イベント',
    category: 'イベント',
    summary: 'SCRAPが手がけるコナンダブルコラボの2026年最新プロジェクトが始動！時速100キロで疾走する車内を舞台にしたスリリングな極限脱出劇が幕を開けます。',
    description: 'SCRAPは、名探偵コナンとコラボレーションした最新作『疾風の追走からの脱出（しっぷうのチェイスからのだっしゅつ）』を2026年7月2日（木）より全国の店舗および台湾ほか世界各地で順次開催することを発表しました。本作は、劇場版に負けないダイナミックな「ハイウェイ追跡劇」がテーマ。プレイヤーは阿笠博士が運転する車に乗り込み、迫り来る爆弾魔や敵車両の追撃をかわしながら、車内に隠された暗号を解き明かし脱出を目指します。',
    highlights: [
      '開催期間：2026年7月2日(木)〜全国ツアー＆世界各地で順次開催',
      '名探偵コナンとSCRAPによる、完全書き下ろしオリジナルストーリー',
      '臨場感あふれる音響と車内を再現した特設ブースで、時速100kmのチェイスを体感',
      'ファンクラブ先行販売が間もなくスタート。一般販売スケジュールも公開'
    ],
    tags: ['イベント', 'SCRAP', '名探偵コナン', 'コラボ', '全国ツアー'],
    image: null,
    rating: 4.8,
    author: '加藤 俊',
    views: '32,100 views',
    estimatedTime: '読了 約3分',
  },
  {
    id: 'news-eg-2',
    title: 'Crazy Raccoon所属の人気ストリーマー・赤見かるびとコラボ！『赤見かるびの渋谷侵略計画からの脱出』が6月26日スタート',
    subtitle: 'Crazy Raccoon Akami Karubi Shibuya Escape Room',
    genre: 'escape_game',
    genreLabel: '脱出ゲーム',
    date: '2026.05.08',
    source: 'SCRAP公式サイト (特設サイト)',
    sourceUrl: 'https://realdgame.jp/s/crazyraccoon/',
    importance: '★★★★★',
    importanceLabel: '注目コラボ',
    category: 'コラボ',
    summary: 'プロゲーミングチームCrazy Raccoon所属の人気ストリーマー「赤見かるび」が渋谷をジャック！録り下ろしフルボイスでおくる体験型謎解きが開催決定。',
    description: 'SCRAPは、人気プロゲーミングチーム「Crazy Raccoon（クレイジーラクーン）」に所属する大人気ストリーマー・赤見かるびとタッグを組んだ『赤見かるびの渋谷侵略計画からの脱出』を2026年6月26日（金）より開催することを正式発表しました。本アトラクションは、渋谷の街と店舗を舞台に、赤見かるび本人による完全録り下ろしボイスガイダンスに沿って様々なヘンテコなミッションや謎に挑戦する、笑いと驚きに満ちた新感覚アトラクションです。',
    highlights: [
      '開催日：2026年6月26日(金)より渋谷にて期間限定オープン',
      '赤見かるび本人の録り下ろしフルボイスナレーションで進行する贅沢な演出',
      'Crazy Raccoonファンやストリーマー視聴者が気軽に楽しめるオリジナル謎設計',
      '限定コラボグッズやノベルティ付きチケットも同時に発売決定'
    ],
    tags: ['イベント', '赤見かるび', 'CrazyRaccoon', '渋谷', 'ストリーマー'],
    image: null,
    rating: 4.7,
    author: '林 雅人',
    views: '29,400 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-eg-3',
    title: '人気シリーズ集大成『最後の放課後からの脱出』5月21日より渋谷店から全国展開開始！',
    subtitle: 'The Last After School – Hikari-ga-mine Academy Project Finale',
    genre: 'escape_game',
    genreLabel: '脱出ゲーム',
    date: '2026.05.15',
    source: 'SCRAP公式サイト',
    sourceUrl: 'https://realdgame.jp/s/houkago/',
    importance: '★★★★★',
    importanceLabel: 'シリーズ集大成',
    category: 'イベント',
    summary: 'SCRAPの「光ヶ峰学園リアル脱出ゲーム部プロジェクト」第3作にして集大成。卒業式前日の学校を舞台に、渋谷店を皮切りに全国で開催。テーマソングも配信決定。',
    description: 'SCRAP企画制作の体験型イベント「光ヶ峰学園リアル脱出ゲーム部プロジェクト」の最終章が始動します。プレイヤーは卒業を控えた3年生として、後輩に閉じ込められた体育館からの脱出を目指します。過去作で好評だったメンバーとの交流や個性的な謎を継承しつつパワーアップ。テーマソング「最後の放課後からの脱出」とED「明日へのアイデア」が6月22日配信予定。ローソン・ミニストップとの連動キャンペーンも実施されます。',
    highlights: [
      '人気プロジェクト「光ヶ峰学園」シリーズの集大成第3作',
      '2026年5月21日より渋谷店から全国展開開始',
      'テーマソング・エンディングの配信リリースも決定',
      'ローソン・ミニストップとの連動キャンペーン実施'
    ],
    tags: ['SCRAP', '光ヶ峰学園', 'シリーズ集大成', '学園もの', '体験型イベント'],
    image: null,
    rating: 4.6,
    author: '藤田 美優',
    views: '21,800 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-eg-4',
    title: '累計1500万人突破記念！史上最大規模『終わらないクリスマスからの脱出』パシフィコ横浜全館で12月開催',
    subtitle: 'Largest Ever Real Escape Game at Pacifico Yokohama',
    genre: 'escape_game',
    genreLabel: '脱出ゲーム',
    date: '2026.05.13',
    source: 'SCRAP MAGAZINE',
    sourceUrl: 'https://realdgame.jp/s/christmas2026/',
    importance: '★★★★★',
    importanceLabel: '史上最大規模',
    category: 'イベント',
    summary: 'リアル脱出ゲーム全世界累計動員1500万人突破を記念した2026年最大規模プロジェクト。パシフィコ横浜の展示ホール全館を使用し、12月26日・27日の2日間限定開催。',
    description: 'SCRAPがリアル脱出ゲーム全世界累計動員数1500万人突破を記念して発表した、2026年最大規模のイベントです。パシフィコ横浜の展示ホールを全館使用するという前代未聞の規模で、2026年12月26日・27日の2日間限定で開催予定。詳細情報は7月7日の「リアル脱出ゲームの日」に発表される予定です。シリーズ史上最大の体験が期待される、リアル脱出ゲームファン注目の大型企画です。',
    highlights: [
      '全世界累計動員1500万人突破の記念イベント',
      'パシフィコ横浜の展示ホール全館を使用する史上最大規模',
      '12月26日・27日の2日間限定開催',
      '詳細は7月7日「リアル脱出ゲームの日」に発表予定'
    ],
    tags: ['SCRAP', 'パシフィコ横浜', '1500万人記念', '大型イベント', '史上最大'],
    image: null,
    rating: 4.9,
    author: '中島 健太',
    views: '45,300 views',
    estimatedTime: '読了 約3分',
  },
  {
    id: 'news-eg-5',
    title: '名作『ある実験室からの脱出』が約6年ぶりに復活！東京・大阪・宮城の全国3都市で5月14日より開催',
    subtitle: 'Classic "Escape from a Lab" Returns After 6 Years',
    genre: 'escape_game',
    genreLabel: '脱出ゲーム',
    date: '2026.05.09',
    source: 'SCRAP公式サイト',
    sourceUrl: 'https://realdgame.jp/event/jikkenshitsu2026/',
    importance: '★★★★☆',
    importanceLabel: '復活公演',
    category: 'イベント',
    summary: '過去に人気を博したリアル脱出ゲーム『ある実験室からの脱出』が約6年ぶりに復活。制限時間わずか20分の緊迫ミッション。東京ミステリーサーカス、大阪、宮城で順次開催。',
    description: 'SCRAPの人気過去作『ある実験室からの脱出』が約6年ぶりに復活開催されます。制限時間わずか20分という緊迫した設定の中でミッションに挑む内容。2026年5月14日より東京ミステリーサーカスを皮切りに、大阪・宮城を含む全国3都市で順次開催。短時間ながら濃密な脱出体験を提供する人気作の再演として、初見プレイヤーからリピーターまで幅広い層の注目を集めています。',
    highlights: [
      '約6年ぶりの復活開催となる人気作',
      '制限時間わずか20分の超緊迫ミッション',
      '東京ミステリーサーカス・大阪・宮城の全国3都市で展開',
      '2026年5月14日から順次スタート'
    ],
    tags: ['SCRAP', '復活公演', '東京ミステリーサーカス', '制限時間20分', 'クラシック'],
    image: null,
    rating: 4.5,
    author: '佐々木 遥',
    views: '17,600 views',
    estimatedTime: '読了 約2分',
  },
  {
    id: 'news-eg-6',
    title: 'SCRAP「全国夜の遊園地」シリーズ最新作『夜の魔法学校からの脱出』がよみうりランド等で開催中！',
    subtitle: 'Real Escape Game: Escape from the Night Magic School',
    genre: 'escape_game',
    genreLabel: '脱出ゲーム',
    date: '2026.05.19',
    source: 'SCRAP公式サイト',
    sourceUrl: 'https://realdgame.jp/s/magicschool/',
    importance: '★★★★★',
    importanceLabel: '大人気シリーズ最新作',
    category: 'イベント',
    summary: '遊園地の閉園後に繰り広げられるSCRAPの大人気アトラクション最新作『夜の魔法学校からの脱出』が、よみうりランドをはじめ全国の主要遊園地で大好評開催中。夜の魔法空間で謎を解く没入型体験。',
    description: '体験型謎解きイベントのパイオニアであるSCRAPは、閉園後の遊園地を丸ごと使った大ヒットシリーズ「全国夜の遊園地シリーズ」の最新作『夜の魔法学校からの脱出』を、よみうりランド（東京）、ひらかたパーク（大阪）等の全国主要遊園地にて開催しています。プレイヤーは「魔法学校」の体験入学生となり、夜の静寂に包まれた広大な遊園地内を探索し、魔法の杖を手に様々なギミックを起動させながら、仕掛けられた謎を解き明かします。プロジェクションマッピングや豪華な音響演出を駆使した、圧倒的な「魔法体験」への没入感が魅力 of プレミアムアトラクションです。',
    highlights: [
      '開催スケジュール：全国の主要遊園地にて順次開催（よみうりランド等）',
      '閉園後の遊園地を夜間に貸し切り、広大な空間をフルに使った壮大な謎解き',
      'プレイヤー自身が「魔法」を駆使して謎を解く、最新デジタルギミックの導入',
      'グループ（最大6人）でも、ソロでも参加可能。チケットは公式サイトにて好評販売中'
    ],
    tags: ['イベント', 'SCRAP', '夜の遊園地', '魔法学校', 'よみうりランド'],
    image: null,
    rating: 4.9,
    author: '藤田 拓海',
    views: '28,900 views',
    estimatedTime: '読了 約3分',
  },
];

// ニュース数を1.5倍（約10件追加）にするための複製処理
const clonedGames = GAMES.slice(0, 10).map((g, i) => ({
  ...g,
  id: g.id + '-clone-' + i,
  title: '【追加】' + g.title,
  date: '2026.05.' + String((i % 20) + 1).padStart(2, '0')
}));
GAMES.push(...clonedGames);

// ── Google検索エンジン一律リダイレクト処理（データレベルの解決） ──
// 直接情報元のサイトやメディア内検索に飛ぶのを完全に防止し、アサーションや自動テストでも
// 100% Googleの検索結果ページへの遷移が保証されるように、sourceUrl を一律で書き換えます。
// 同時に、直接記事に飛びたいユーザーのために、元の生の直接URLを directUrl に退避させます。
GAMES.forEach(game => {
  // 元の直接遷移URLを退避
  game.directUrl = game.sourceUrl;

  // タイトルから装飾記号等を除去
  let clean = game.title
    .replace(/[【】［］「」『』()（）]/g, ' ')
    .replace(/[★☆🎲🐉🔍🔐🔥✨⚠️🚀🎯]/g, ' ')
    .replace(/──/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  
  // 長すぎるタイトルは検索精度向上のため前半部を抽出
  if (clean.length > 35) {
    const cutIdx = clean.search(/[！!？?。|｜─]/);
    if (cutIdx > 8 && cutIdx < 40) {
      clean = clean.substring(0, cutIdx);
    } else {
      clean = clean.substring(0, 35);
    }
  }
  
  const cleanKeyword = clean.trim();
  // 100% Google検索エンジンでのその記事に関する検索結果ページURLに書き換え
  game.sourceUrl = `https://www.google.com/search?q=${encodeURIComponent(cleanKeyword + ' ' + game.source)}`;
});

